@x64

[export:yes]
[entry:yes]
[integer64:yes]
(i64[] a)main(i32? res)
{
    ?(a, 0, ?a)quick_sort(*);
    i64 x, sum;
    sum <- x <- 0;
    while x < ?a
    {
        sum <- sum + a[x] * x;
        x <- x + 1;
    }
    res <- `i32`sum;
}
 

[integer64:yes]
(i64[] arr, i64 l, i64 r)insertion_sort(i32? res)
{
    i64 i, j, pivot, val;
    i <- l;
    while i < r
    {
        pivot <- arr[i];
        j <- i;
        while j > l && arr[j - 1] > pivot
        {
            arr[j] <- arr[j - 1];
            j <- j - 1;
        }
        arr[j] <- pivot;
        i <- i + 1;
    }
    res <- `i32`0;
}

[integer64:yes]
(i64[] arr, i64 pivot_index, i64 l, i64 r)split(i64? left, i64? right)
{
    i64 pivot, i, j, tmp;
    pivot <- arr[pivot_index];

    # make interval include r
    r <- r - 1;
    
    # save pivot in the end
    tmp <- arr[r];
    arr[r] <- arr[pivot_index];
    arr[pivot_index] <- tmp;
    
    i <- l;
    j <- r - 1;

    while i < j
    {
        while i < r && arr[i] < pivot
        {
            i <- i + 1;
        }
        while j >= l && arr[j] > pivot
        {
            j <- j - 1;
        }
        match i < j {`i32`-1{
            tmp <- arr[i];
            arr[i] <- arr[j];
            arr[j] <- tmp;
            i <- i + 1;
            j <- j - 1;
        }}
    }

    tmp <- arr[i];
    arr[i] <- arr[r];
    arr[r] <- tmp;

    left <- i;
    right <- i + 1;
}

[integer64:yes]
(i64[] arr, i64 l, i64 r)quick_sort(i32? res)
{
    i32?[] calls;
    i64 calls_cnt;
    calls <- new i32?[](32);
    calls_cnt <- 0;
    while r - l > 128
    {
        i64 pivot_index;
        pivot_index <- (l + r) / 2;
        i64 lt, gt;
        (arr, pivot_index, l, r)split(var plt, var pgt);
        lt <- ?plt;
        gt <- ?pgt;

        match lt < r - gt
        {
            `i32`-1 {
                calls[calls_cnt] <- (arr, l, lt)quick_sort(*);
                calls_cnt <- calls_cnt + 1;
                l <- gt;
            } `i32`0 {
                calls[calls_cnt] <- (arr, gt, r)quick_sort(*);
                calls_cnt <- calls_cnt + 1;
                r <- lt;
            }
        }
    }
    ?(arr, l, r)insertion_sort(*);

    i64 id;
    id <- 0;
    while id < calls_cnt
    {
        ?calls[id];
        id <- id + 1;
    }
    
    res <- `i32`0;
}
