// this sourse file was generated using grammar.fsx
#include <vector>
#include <map>
using namespace std;
#include "ast.hpp"
Rule *grammar;
int64_t grammar_len;
Rule *generateGrammar()
{
// allocate memory for all elements
grammar_len = 56;
Rule *array = (Rule *)malloc(sizeof(*array) * grammar_len);
new(array + 1)Rule(1, "S", vector<RuleVariant>{RuleVariant(0, vector<Atom>{grammar_fn_spaces})});
new(array + 2)Rule(2, "Sn", vector<RuleVariant>{RuleVariant(0, vector<Atom>{grammar_fn_spaces_or_no})});
new(array + 3)Rule(3, "identifer", vector<RuleVariant>{RuleVariant(0, vector<Atom>{grammar_fn_identifer})});
new(array + 4)Rule(4, "identifer_or_number", vector<RuleVariant>{RuleVariant(0, vector<Atom>{grammar_fn_identifer_or_number})});
new(array + 5)Rule(5, "integer", vector<RuleVariant>{RuleVariant(0, vector<Atom>{grammar_fn_integer})});
new(array + 6)Rule(6, "float", vector<RuleVariant>{RuleVariant(0, vector<Atom>{grammar_fn_float})});
new(array + 7)Rule(7, "quotedstring", vector<RuleVariant>{RuleVariant(0, vector<Atom>{grammar_fn_quotedstring})});
new(array + 20)Rule(20, "AddOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 26, array + 34}, vector<Atom>{array + 26, array + 34}, vector<Atom>{array + 26}), RuleVariant(1, vector<Atom>{array + 26}, vector<Atom>{}, vector<Atom>{})});
new(array + 21)Rule(21, "BinOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 27, array + 37}, vector<Atom>{array + 27, array + 37}, vector<Atom>{array + 27}), RuleVariant(1, vector<Atom>{array + 27}, vector<Atom>{}, vector<Atom>{})});
new(array + 22)Rule(22, "CompareOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 20, array + 41}, vector<Atom>{array + 20, array + 41}, vector<Atom>{array + 20}), RuleVariant(1, vector<Atom>{array + 20}, vector<Atom>{}, vector<Atom>{})});
new(array + 23)Rule(23, "Global", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 1}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 32}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 33}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 31}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 53}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 54}, vector<Atom>{}, vector<Atom>{})});
new(array + 24)Rule(24, "IndexOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 30, array + 2, "[", array + 43, array + 2, "]"}, vector<Atom>{".", array + 3}, vector<Atom>{}), RuleVariant(1, vector<Atom>{array + 30}, vector<Atom>{}, vector<Atom>{})});
new(array + 25)Rule(25, "LogicOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 22, array + 44}, vector<Atom>{array + 22, array + 44}, vector<Atom>{array + 22}), RuleVariant(1, vector<Atom>{array + 22}, vector<Atom>{}, vector<Atom>{})});
new(array + 26)Rule(26, "MulOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 21, array + 45}, vector<Atom>{array + 21, array + 45}, vector<Atom>{array + 21}), RuleVariant(1, vector<Atom>{array + 21}, vector<Atom>{}, vector<Atom>{})});
new(array + 27)Rule(27, "PrefixOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 47, array + 27}, vector<Atom>{}, vector<Atom>{}), RuleVariant(1, vector<Atom>{array + 28}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "(", array + 51, array + 2, ")", array + 27}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "`", array + 51, array + 2, "`", array + 27}, vector<Atom>{}, vector<Atom>{})});
new(array + 28)Rule(28, "QueryOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 36, array + 2, "?", array + 27}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 24, array + 36, array + 2, "?", array + 2, array + 27}, vector<Atom>{}, vector<Atom>{}), RuleVariant(1, vector<Atom>{array + 24}, vector<Atom>{}, vector<Atom>{})});
new(array + 29)Rule(29, "SetOperation", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 28, array + 2, "<-"}, vector<Atom>{array + 28, array + 2, "<-"}, vector<Atom>{array + 25}), RuleVariant(1, vector<Atom>{array + 25}, vector<Atom>{}, vector<Atom>{})});
new(array + 30)Rule(30, "SimpleTerm", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, array + 46}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, array + 5}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, array + 6}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, array + 3}, vector<Atom>{".", array + 3}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "(", array + 38, array + 2, ")", array + 2, array + 3, array + 36, array + 2, "(", array + 39, array + 2, ")"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(1, vector<Atom>{array + 2, "(", array + 43, array + 2, ")"}, vector<Atom>{}, vector<Atom>{})});
new(array + 31)Rule(31, "_class", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "class", array + 1, array + 3, array + 2, "{"}, vector<Atom>{array + 50, array + 2, ";"}, vector<Atom>{array + 2, "}"})});
new(array + 32)Rule(32, "_record", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "struct", array + 1, array + 3, array + 2, "{"}, vector<Atom>{array + 50, array + 2, ";"}, vector<Atom>{array + 2, "}"})});
new(array + 33)Rule(33, "_union", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "union", array + 1, array + 3, array + 2, "{"}, vector<Atom>{array + 50, array + 2, ";"}, vector<Atom>{array + 2, "}"})});
new(array + 34)Rule(34, "add_op", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "+"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "-"}, vector<Atom>{}, vector<Atom>{})});
new(array + 35)Rule(35, "arguments_list", vector<RuleVariant>{RuleVariant(0, vector<Atom>{}, vector<Atom>{array + 51, array + 1, array + 3, array + 2, ","}, vector<Atom>{array + 51, array + 1, array + 3}), RuleVariant(0, vector<Atom>{}, vector<Atom>{array + 51, array + 1, array + 3, array + 2, ","}, vector<Atom>{})});
new(array + 36)Rule(36, "attribute_list", vector<RuleVariant>{RuleVariant(0, vector<Atom>{}, vector<Atom>{array + 2, "[", array + 2, array + 4, array + 2, ":", array + 2, array + 4, array + 2, "]"}, vector<Atom>{})});
new(array + 37)Rule(37, "bin_op", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "|"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "&"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "^"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "<<"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, ">>"}, vector<Atom>{}, vector<Atom>{})});
new(array + 38)Rule(38, "call_arg_list", vector<RuleVariant>{RuleVariant(0, vector<Atom>{}, vector<Atom>{array + 43, array + 2, ","}, vector<Atom>{array + 43}), RuleVariant(0, vector<Atom>{}, vector<Atom>{array + 43, array + 2, ","}, vector<Atom>{})});
new(array + 39)Rule(39, "call_result_list", vector<RuleVariant>{RuleVariant(0, vector<Atom>{}, vector<Atom>{array + 48, array + 2, ","}, vector<Atom>{array + 48}), RuleVariant(0, vector<Atom>{}, vector<Atom>{array + 48, array + 2, ","}, vector<Atom>{})});
new(array + 40)Rule(40, "case_branch", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "default", array + 42}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 43, array + 42}, vector<Atom>{}, vector<Atom>{})});
new(array + 41)Rule(41, "cmp_op", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "<>"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, ">="}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "<="}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, ">"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "<"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "="}, vector<Atom>{}, vector<Atom>{})});
new(array + 42)Rule(42, "code_block", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "{"}, vector<Atom>{array + 49}, vector<Atom>{array + 2, "}"})});
new(array + 43)Rule(43, "expression", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 29}, vector<Atom>{}, vector<Atom>{})});
new(array + 44)Rule(44, "logic_op", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "&&"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "||"}, vector<Atom>{}, vector<Atom>{})});
new(array + 45)Rule(45, "mul_op", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "*"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "/"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "%"}, vector<Atom>{}, vector<Atom>{})});
new(array + 46)Rule(46, "new_operator", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "new", array + 1, array + 51, array + 36, array + 2, "(", array + 38, array + 2, ")"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "new", array + 1, array + 51, array + 36, array + 2, array + 7}, vector<Atom>{}, vector<Atom>{})});
new(array + 47)Rule(47, "prefix_op", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "+"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "-"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "!"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "~"}, vector<Atom>{}, vector<Atom>{})});
new(array + 48)Rule(48, "result_list_identifer", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "*"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, array + 3}, vector<Atom>{}, vector<Atom>{})});
new(array + 49)Rule(49, "statement", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 50, array + 2, ";"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 43, array + 2, ";"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "while", array + 43, array + 42}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "match", array + 43, array + 2, "{"}, vector<Atom>{array + 40}, vector<Atom>{array + 2, "}"})});
new(array + 50)Rule(50, "var_declaration", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 51, array + 1, array + 3}, vector<Atom>{array + 2, ",", array + 2, array + 3}, vector<Atom>{array + 2, ","}), RuleVariant(0, vector<Atom>{array + 51, array + 1, array + 3}, vector<Atom>{array + 2, ",", array + 2, array + 3}, vector<Atom>{})});
new(array + 51)Rule(51, "var_type", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, array + 3}, vector<Atom>{array + 52}, vector<Atom>{})});
new(array + 52)Rule(52, "var_type_moditifer", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 2, "[]"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "|"}, vector<Atom>{}, vector<Atom>{}), RuleVariant(0, vector<Atom>{array + 2, "?"}, vector<Atom>{}, vector<Atom>{})});
new(array + 53)Rule(53, "worker", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 36, array + 2, "(", array + 35, array + 2, ")", array + 2, array + 3, array + 2, "(", array + 35, array + 2, ")", array + 42}, vector<Atom>{}, vector<Atom>{})});
new(array + 54)Rule(54, "worker_decl", vector<RuleVariant>{RuleVariant(0, vector<Atom>{array + 36, array + 2, "(", array + 35, array + 2, ")", array + 2, array + 3, array + 2, "(", array + 35, array + 2, ")", array + 2, ";"}, vector<Atom>{}, vector<Atom>{})});
return array;
}