@x64

[entry:true]
[export:true]
(i64[] input)main(i32? result)
{
    i64 handle;
    i32 game_width, game_height;
    i32 key, timer, posy;

    handle <- ?()initscr@dll(*);
    ?()noecho@dll(*);
    ?()cbreak@dll(*);
    ?(0)curs_set@dll(*);
    ?(handle, 1)keypad@dll(*);
    ?(handle, 1)nodelay@dll(*);
    
    game_width <- ?(handle)getmaxx@dll(*);
    game_height <- ?(handle)getmaxy@dll(*);
    
    timer <- 0;
    posy <- 2;

    while (key <- ?(handle)wgetch@dll(*)) <> 113
    {
        # ?(new i8[]"!!!")puts@dll(*);
        ?(new i8[]">%d<\n", key)printd@dll(*);
        match key
        {
            260 { # left
                
            }

            271 { # right
                
            }

            258 { # down
                posy <- posy + 1;
            }
        }

        timer <- timer + 1;
        match timer
        {
            10 {
                posy <- posy + 1;
                timer <- 0;
            }
        }

        ?(handle)wclear@dll(*);
        ?(handle, game_width, game_height)draw_frame(*);
        
        # ?(handle, posy, 5, `i64`35)mvwaddch@dll(*);
        
        ?(handle)wrefresh@dll(*);
        sleep 50;
    }

    ?()endwin@dll(*);
    result <- 0;
}


(i64 handle, i32 w, i32 h)draw_frame(i32? result)
{
    i32 i;
    i <- 0;
    while i < h
    {
        # ?(handle, i, 0, `i64`124)mvwaddch@dll(*);
        # ?(handle, i, w - 1, `i64`124)mvwaddch@dll(*);
        i <- i + 1;
    }
    i <- 0;
    while i < w
    {
        # ?(handle, h - 1, i, `i64`45)mvwaddch@dll(*);
    }
    result <- 0;
}


[dllimport:libncursesw.so]
()initscr(i64? handle);

[dllimport:libncursesw.so]
()noecho(i32? result);

[dllimport:libncursesw.so]
()cbreak(i32? result);

[dllimport:libncursesw.so]
(i32 shown)curs_set(i32? result);

[dllimport:libncursesw.so]
(i64 handle, i32 bool)keypad(i32? result);

[dllimport:libncursesw.so]
(i64 handle, i32 bool)nodelay(i32? result);

[dllimport:libncursesw.so]
(i64 handle, i32 y, i32 x, i64 char)mvwaddch(i32? result);

[dllimport:libncursesw.so]
(i64 handle)wclear(i32? result);

[dllimport:libncursesw.so]
(i64 handle)wgetch(i32? result);

[dllimport:libncursesw.so]
(i64 handle)wrefresh(i32? result);

[dllimport:libncursesw.so]
()endwin(i32? result);

[dllimport:libncursesw.so]
(i64 handle)getmaxx(i32? result);

[dllimport:libncursesw.so]
(i64 handle)getmaxy(i32? result);

[dllimport:libc.so]
(i64 zero)time(u64? time);

[dllimport:libc.so]
(i8[] msg)puts(u32? res);

[dllimport:libc.so]
[dllimport.entry:printf]
(i8[] format, i32 value)printd(u32? res);
