@x64

[entry:yes]
[export:yes]
(i64[] input)main(i32? res)
{
    # read args
    i64 W, H, size, era_count;
    i32 count;
    W <- input[0];
    H <- input[1];
    era_count <- input[2];
    count <- `i32`input[3];
    size <- W * H;

    # create cpu buffer
    i8[] buffer;
    buffer <- new i8[](size);

    i16[] output_buffer;
    output_buffer <- new i16[]((W + `i64`1) * H * `i64`2 + `i64`2);

    # set state
    ?(buffer, W, H, count)Init(*);

    # get console + create strings
    i64 handle;
    # handle <- ?(-11)GetStdHandle@dll(*);
    handle <- ?(`u32`0x80000000|`u32`0x40000000, 1 | 2, 0, 0x01, 0)CreateConsoleScreenBuffer@dll(*);
    ?(handle)SetConsoleActiveScreenBuffer@dll(*);

    # create gpu buffers
    i8[]@gpu gpu_tmp;
    i8[]@gpu gpu_A;
    i8[]@gpu gpu_B;
    gpu_A <- `i8[]@gpu`buffer;
    gpu_B <- `i8[]@gpu`buffer;

    i32 step, max_steps;
    step <- 0;
    max_steps <- 100000;

    # draw before running
    ?(handle, output_buffer, W, H, buffer)Draw(*);

    while step < max_steps
    {
        # step forward
        i64 id;
        id <- `i64`0;
        while id < era_count && step < max_steps
        {
            ?(gpu_A, gpu_B, W, H, `i64`0, `i64`0)life_step@gpu(*);
            gpu_tmp <- gpu_A;
            gpu_A <- gpu_B;
            gpu_B <- gpu_tmp;
            step <- step + 1;
            id <- id + `i64`1;
        }

        # draw state
        buffer <- `i8[]`gpu_A;
        ?(handle, output_buffer, W, H, buffer)Draw(*);

        sleep 50;
    }

    # final draw
    buffer <- `i8[]`gpu_A;
    ?(handle, output_buffer, W, H, buffer)Draw(*);
    
    res <- 0;
}

(i64 handle, i16[] output_buffer, i64 W, i64 H, i8[] buffer)Draw(i32? res)
{
    # print field
    i64 pos;
    pos <- 0;
    coord zero;
    zero.x <- zero.y <- `i16`0;
    ?(handle, zero)SetConsoleCursorPosition@dll(*);
    i64 x, y;
    y <- `i64`0;
    while y < H
    {
        x <- `i64`0;
        while x < W
        {
            match `i32`buffer[y*W + x]
            {
                0 {
                    output_buffer[pos+`i64`0] <- `i16`32;
                    output_buffer[pos+`i64`1] <- `i16`32;
                    pos <- pos + `i64`2;
                } 1 {
                    output_buffer[pos+`i64`0] <- `i16`91;
                    output_buffer[pos+`i64`1] <- `i16`93;
                    pos <- pos + `i64`2;
                }
            }
            x <- x + `i64`1;
        }
        output_buffer[pos] <- `i16`10;
        pos <- pos + `i64`1;
        y <- y + `i64`1;
    }
    output_buffer[pos] <- `i16`0;
    ?(handle, output_buffer, pos, `i64`0, `i64`0)WriteConsole@dll(*);
    res <- 0;
}


(i8[] buffer, i64 W, i64 H, i32 count)Init(i32? res)
{
    # create 5 galactics, of size (W+H)/20
    i64 size;
    size <- (W + H)/20 + `i64`2;

    i32 cnt;
    u64 p;
    p <- ?()GetTickCount64@dll(*);
    cnt <- 0;
    while cnt < count
    {

        i64 x, y, sx, sy;
        sx <- `i64`(p/`u64`59811%`u64`W);
        sy <- y <- `i64`(p/`u64`24812%`u64`H);
        while y < sy+size
        {
            x <- sx;
            while x < sx+size
            {
                buffer[(y%H)*W + (x%W)] <- `i8`-(p / `u64`1000000009 % `u64`100 < `u64`23); # 23% live cells
                p <- p * `u64`998244353 + `u64`57;
                x <- x + `i64`1;
            }
            y <- y + `i64`1;
        }
        
        cnt <- cnt + 1;
    }
    res <- 0;
}

@gpu

[GPUxVariable:x]
[GPUyVariable:y]
[GPUxSize:W]
[GPUySize:H]
[integer64:yes]
(i8[] src, i8[] dst, i64 W, i64 H, i64 x, i64 y)life_step(i32?@x64 await)
{
    i64 nx, ny, live, dy, dx;
    i8 current_state;
    
    current_state <- src[y*W + x];
    live <- -`i64`current_state;
    
    dy <- H-1;
    while dy <= H+1 
    {
        dx <- W-1;
        while dx <= W+1 
        {
            ny <- (y + dy) % H;
            nx <- (x + dx) % W;
            live <- live + `i64`src[ny*W + nx];
            dx <- dx + 1;
        }
        dy <- dy + 1;
    }


    dst[y*W + x] <- `i8`(-(live = 3 || (live = 2 && current_state = `i8`1)));
}

@x64

[dllimport:kernel32.dll]
(i32 nStdHandle)GetStdHandle(i64? hHandle);

[dllimport:kernel32.dll]
(u32 access, i32 share, i64 null, i32 flags, i64 reserved)CreateConsoleScreenBuffer(i64? hHandle);

[dllimport:kernel32.dll]
(i64 handle)SetConsoleActiveScreenBuffer(i32? res);

[dllimport:kernel32.dll]
[dllimport.entry:CreateConsoleScreenBuffer]
(i32 nStdHandle)CreateConsoleScreenBuffer(i64? hHandle);

[dllimport:kernel32.dll]
[dllimport.entry:WriteConsoleW]
(
    i64     hConsoleOutput,
    i16[]   lpBuffer,
    i32     nNumberOfCharsToWrite,
    i32?    lpNumberOfCharsWritten,
    i64     lpReserved
)WriteConsole(i32? result);

struct coord
{
    i16 x, y;
}

[dllimport:kernel32.dll]
(
    i64     hConsoleOutput, 
    coord   coords
)SetConsoleCursorPosition(i32? result);


[dllimport:kernel32.dll]
()GetTickCount64(u64? time);

