@x64


[noinline:true]
()print1(i32? res)
{
    i64 handle;
    handle <- ?(-11)GetStdHandle@dll(*); # get stdout handle
    i16[] msg;
    msg <- new i16[]"Hello Remote World!\n"; # create message
    res <- ?(handle, msg, `i32`?msg, `i64`0, `i64`0)WriteConsole@dll(*); # print it
}

[noinline:true]
()print2(i32? res)
{
    i64 handle;
    handle <- ?(-11)GetStdHandle@dll(*); # get stdout handle
    i16[] msg;
    msg <- new i16[]"Hello Local World!\n"; # create message
    res <- ?(handle, msg, `i32`?msg, `i64`0, `i64`0)WriteConsole@dll(*); # print it
}

[export:yes]
[entry:yes]
(i64[] input)main(i32? res) 
{
    while -1
    {
        ?()print1[on:remote](*);
        ?()print2[on:local](*);
        sleep 1000;
    }
}

[dllimport:kernel32.dll]
[dllimport.entry:GetStdHandle]
(i32 nStdHandle)GetStdHandle(i64? hHandle);

[dllimport:kernel32.dll]
[dllimport.entry:WriteConsoleW]
(
    i64     hConsoleOutput,
    i16[]   lpBuffer,
    i32     nNumberOfCharsToWrite,
    i32?    lpNumberOfCharsWritten,
    i64     lpReserved
)WriteConsole(i32? result);

